---
  - name: Generate a random password
    ansible.builtin.set_fact:
      password: "{{ generator }}"
    tags: linux
  - name: "Set password for user {{ item }}"
    ansible.builtin.user:
      name: "{{ item }}"
      password: "{{ password | password_hash('sha512') }}"
    tags: linux
  - name: "Add {{ item }}: {{ password }} to password file"
    ansible.builtin.lineinfile:
      path: "passwords-{{ inventory_hostname }}.txt"
      regexp: "^{{ item }}: "
      line: "{{ item }}: {{ password }}"
      create: true
    delegate_to: localhost
    tags: linux
...