---
  - name: Generate a random password
    ansible.builtin.set_fact:
      password: "#{{ generator }}@"
    tags: windows
  - name: "Set password for user {{ item }}"
    ansible.windows.win_user:
      name: "{{ item }}"
      password: "{{ password }}"
    tags: windows
  - name: "Add {{ item }}: {{ password }} to password file"
    ansible.builtin.lineinfile:
      path: "passwords-{{ inventory_hostname }}.txt"
      regexp: "^{{ item }}: "
      line: "{{ item }}: {{ password }}"
      create: true
    delegate_to: localhost
    tags: windows
...